### ISSUE TITLE
CPP98 support introduces syntax error in std::vector with MSVC 19.44

### ISSUE THREAD

**Issue by shoeffner** [ismrmrd/ismrmrd#267]
**Describe the bug**
The `#define noexcept` in `include/ismrmrd/cpp98.h` causes recent MSVC (Microsoft (R) C/C++ Optimizing Compiler Version 19.44.35222 for x64) to fail to compile a simple test program due to `std::vector<>` template initialization errors.

Removing it resolves the errors (in the Release build, I am still working on Debug). It works fine on gcc11 and gcc13.

**To Reproduce**
We are building ismrmrd with conan to link against it at a later state. To ensure everything works fine, I have a simple example test program (our test is longer but for reproduction of the issue, this is more than sufficient):
```cpp
#include <iostream>
#include <ismrmrd/ismrmrd.h>
#include <ismrmrd/dataset.h>
#include <ismrmrd/serialization.h>

/**
 * @see https://ismrmrd.readthedocs.io/en/latest/cpplibrary.html#c-support-library
 */
int main()
{
  // Dummy header
  std::string xml("<ismrmrdHeader xsi:schemaLocation=\"http://www.ismrm.org/ISMRMRD ismrmrd.xsd\"><version>1</version><experimentalConditions></experimentalConditions><encoding><trajectory>cartesian</trajectory><encodedSpace><matrixSize><x>1</x><y>1</y><z>1</z></matrixSize><fieldOfView_mm><x>1</x><y>1</y><z>1</z></fieldOfView_mm></encodedSpace><reconSpace><matrixSize><x>1</x><y>1</y><z>1</z></matrixSize><fieldOfView_mm><x>1</x><y>1</y><z>1</z></fieldOfView_mm></reconSpace><encodingLimits></encodingLimits></encoding></ismrmrdHeader>");
  ISMRMRD::IsmrmrdHeader hdr;
  ISMRMRD::deserialize(xml.c_str(), hdr);
  if (!hdr.version)
  {
    std::cerr << "Could not load XML header" << std::endl;
    return -1;
  }

  std::cout << "Success: Can parse xml" << std::endl;
}
```
which is built with this CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.24)
cmake_policy(SET CMP0091 ${CMAKE_POLICY_DEFAULT_CMP0091})  # this is for conan, don't remember exactly why -- irrelevant here
project(PackageTest CXX)

find_package(ISMRMRD REQUIRED)

add_executable(example example.cpp)
target_link_libraries(example ISMRMRD::ISMRMRD)
```

In fact, this example should be enough to reproduce the issue (though I have to admit I didn't compile it right now, I just had it briefly during my debugging session):
```cpp
#include <ismrmrd/cpp98.h>
#include <vector>
class Test {
    std::vector<float> test;
};
int main() { return 0; }
```

Compiling this program with MSVC does not work with versions later than 1.13.7 (i.e., 1.14.0 introduced the issue).
It fails with syntax errors in `<vector>`, see logs below.

**Expected behavior**
The code should compile.

**Logs/Screenshots**
I shortened the logs, the list is much longer: basically every `std::vector<X>` declaration in `xml.h` will fail, also in ismrmrd.h and others.
```
09:49:32  ismrmrd/1.14.3@fme/stable (test package): Running CMake.build()
09:49:32  ismrmrd/1.14.3@fme/stable (test package): RUN: cmake --build "c:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug" --config Debug -- /m:30
09:49:32  MSBuild version 17.14.40+3e7442088 for .NET Framework
09:49:33  
09:49:34    1>Checking Build System
09:49:34    Building Custom Rule C:/ws/47c292c03/debug/recipe/test_package/CMakeLists.txt
09:49:35    example.cpp
09:49:36  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(670,36): error C2061: syntax error: identifier '?$is_nothrow_default_constructible_v@$std:?$allocator_traits@$RBAAC@:rebind_alloc<$RBAAB@>:' [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
09:49:36    (compiling source file '../../example.cpp')
09:49:36        C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(670,36):
09:49:36        the template instantiation context (the oldest one first) is
09:49:36            C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(442,7):
09:49:36            while compiling class template 'std::vector'
...
09:49:36  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(670,36): error C2061: syntax error: identifier 'is_nothrow_default_constructible_v<std::allocator<ISMRMRD::MeasurementDependency> >' [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
09:49:36    (compiling source file '../../example.cpp')
09:49:36        C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(670,36):
09:49:36        the template instantiation context (the oldest one first) is
09:49:36            C:\conan_cache\b\ismrm0c1ce62105949\p\include\ismrmrd\xml.h(204,40):
09:49:36            see reference to class template instantiation 'std::vector<ISMRMRD::MeasurementDependency,std::allocator<ISMRMRD::MeasurementDependency>>' being compiled
...
```

**System Information:**
 - OS: Windows (docker container) with MSVC 19.44.35222; does **not** occur on Linux with gcc11 or gcc13 
 - Install/deployment method: docker image with a local compilation; I build ismrmrd and then link to it from an example program
 - Version: 14e5abdd189b6d8fc9f7e020ad3d37fafef115c7 and later (I tried up until 1.15.0)
 - Our conan profile sets the CMAKE_CXX_STANDARD to 20 by default

**Additional context**
I was updating to support CMake 4, so I had to update ismrmrd from 1.13.7 to 1.14.x or later. With 1.14.3 and 1.15.0 I had the above error so I tracked it down.

The issue was introduced with this line in the commit adding cpp98 support:

https://github.com/ismrmrd/ismrmrd/blob/14e5abdd189b6d8fc9f7e020ad3d37fafef115c7/include/ismrmrd/cpp98.h#L31

I believe this causes issues because it defines `noexcept` for the pre-processor and that causes issues with the std::vector template as defined here: https://en.cppreference.com/w/cpp/header/vector.html#Class_template_std::vector because all the noexcepts will be dropped, causing the aforementioned syntax errors.
I assume that this is because of solving the issue of older compilers not supporting noexcept – the more common case seems to be to define a custom NOEXCEPT and either set it to noexcept or leave it empty; there are a couple of similar things at stackoverflow here: https://stackoverflow.com/a/33298731 . I am not sure though.
Once I remove the `#define noexcept` line, Release built fine again.

For Debug, I now run into the following, which may or may not be related:
```
16:32:42    1>Checking Build System
16:32:43    Building Custom Rule C:/ws/47c292c03/debug/recipe/test_package/CMakeLists.txt
16:32:45    example.cpp
16:32:48  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42): error C2440: '=': cannot convert from 'int' to '_Ty' [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
16:32:48  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42): error C2440:         with [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
16:32:48  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42): error C2440:         [ [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
16:32:48  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42): error C2440:             _Ty=std::_Container_proxy * [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
16:32:48  C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42): error C2440:         ] [C:\ws\47c292c03\debug\recipe\test_package\build\msvc-194-x86_64-20-debug\example.vcxproj]
16:32:48    (compiling source file '../../example.cpp')
16:32:48        C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42):
16:32:48        Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast
16:32:48        C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\utility(774,42):
16:32:48        the template instantiation context (the oldest one first) is
16:32:48            C:\conan_cache\b\ismrmc97df99462014\p\include\ismrmrd\xml.h(563,38):
16:32:48            see reference to class template instantiation 'std::vector<ISMRMRD::WaveformInformation,std::allocator<ISMRMRD::WaveformInformation>>' being compiled
16:32:48            C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(829,19):
16:32:48            while compiling class template member function 'std::vector<ISMRMRD::WaveformInformation,std::allocator<ISMRMRD::WaveformInformation>>::~vector(void) noexcept'
16:32:48                C:\conan_cache\b\ismrmc97df99462014\p\include\ismrmrd\xml.h(564,3):
16:32:48                see the first reference to 'std::vector<ISMRMRD::WaveformInformation,std::allocator<ISMRMRD::WaveformInformation>>::~vector' in 'ISMRMRD::IsmrmrdHeader::IsmrmrdHeader'
16:32:48            C:\BuildTools\VC\Tools\MSVC\14.44.35207\include\vector(833,47):
16:32:48            see reference to function template instantiation '_Ty *std::exchange<std::_Container_proxy*,int>(_Ty &,_Other &&) noexcept(false)' being compiled
16:32:48            with
16:32:48            [
16:32:48                _Ty=std::_Container_proxy *,
16:32:48                _Other=int
16:32:48            ]
16:32:48    
16:32:48  
16:32:48  [31mERROR: ismrmrd/1.15.0@fme/stable (test package): Error in build() method, line 33
16:32:48    super().build()
16:32:48    ConanException: Error 1 while executing[0m
16:32:49  [0m
```
