### ISSUE TITLE
Boost:unit_test error on OpenSuse 13.2

### ISSUE THREAD

**Issue by ckolbitsch** [ismrmrd/ismrmrd#45]
Hi,

I tried to compile ismrmrd on OpenSuse 13.2 and if I call make I get the following errors:

Building info application
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   program_options
FFTW3 UNIX libraries: /usr/lib64/libfftw3f.so
FFTW3 and Boost Found... building utilities
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   unit_test_framework
CPACK_PACKAGING_INSTALL_PREFIX: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /data/general/GADGETRON/ismrmrd/build
[ 31%] Built target ismrmrd
[ 40%] Built target ismrmrd_generate_cartesian_shepp_logan
[ 45%] Built target ismrmrd_info
[ 50%] Built target ismrmrd_read_timing_test
[ 54%] Built target ismrmrd_recon_cartesian_2d
[ 63%] Built target ismrmrd_test_xml
[ 68%] Built target ismrmrd_c_example
Linking CXX executable test_ismrmrd
CMakeFiles/test_ismrmrd.dir/test_acquisitions.cpp.o: In function `bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, ISMRMRD::ISMRMRD_ErrorCodes>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, ISMRMRD::ISMRMRD_ErrorCodes const&, char const*) [clone .constprop.95]':
test_acquisitions.cpp:(.text+0x116): undefined reference to`boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
[LOTS AND LOTS MORE ERROR MESSAGES]
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_ismrmrd.dir/build.make:241: recipe for target 'tests/test_ismrmrd' failed
make[2]: **\* [tests/test_ismrmrd] Error 1
CMakeFiles/Makefile2:501: recipe for target 'tests/CMakeFiles/test_ismrmrd.dir/all' failed
make[1]: **\* [tests/CMakeFiles/test_ismrmrd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

I was just wondering if anyone has had a similar problem or if it just might have something to do with the fact that I try to install it on OpenSuse and not Ubuntu.

Thanks!
Christoph

**Comment by ghisvail** [comment]
Sounds to me that `Boost.Test` is the culprit. The upstream changelog mentions that `Boost 1.59` features a new major release of `Boost.Test`, so they might have broken something. You could try out with `Boost 1.58` instead, which I confirm the test suite works with.

**Comment by naegelejd** [comment]
The unit tests compile and run with Boost 1.59 on Mac OS X, so they *should* work with Boost 1.59 in general.

**Comment by hansenms** [comment]
This looks like a linking error, could it be that you have upgraded and you have a left over build in your build folder. Could you try to clean out your build folder and try again?

**Comment by ckolbitsch** [comment]
Thanks for your suggestions.  

I changed my boost version from 1.59 to 1.54 and both ismrmrd and gadgetron compiled fine and I could run the "Hello World" test.
