### ISSUE TITLE
make failed on Ubuntu

### ISSUE THREAD

**Issue by frankong** [ismrmrd/ismrmrd#94]
I was able to follow the installation instructions up to make, and got the following error:

[ 26%] Built target ismrmrd
[ 36%] Built target ismrmrd_generate_cartesian_shepp_logan
[ 43%] Built target ismrmrd_read_timing_test
[ 50%] Built target ismrmrd_info
[ 56%] Built target ismrmrd_recon_cartesian_2d
[ 66%] Built target ismrmrd_test_xml
[ 70%] Linking C executable ismrmrd_c_example
../../libismrmrd.so.1.3.3: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
../../libismrmrd.so.1.3.3: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
examples/c/CMakeFiles/ismrmrd_c_example.dir/build.make:101: recipe for target 'examples/c/ismrmrd_c_example' failed
make[2]: *** [examples/c/ismrmrd_c_example] Error 1
CMakeFiles/Makefile2:450: recipe for target 'examples/c/CMakeFiles/ismrmrd_c_example.dir/all' failed
make[1]: *** [examples/c/CMakeFiles/ismrmrd_c_example.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Any advice on how to compile? Thanks!

**Comment by hansenms** [comment]
Which version of Ubuntu are you on?

**Comment by frankong** [comment]
Thanks for the response. Able to install after a clean.

**Comment by LElgueddari** [comment]
I got the same issue, I tried the make clean but it doesn't remove the error.
I'm on Ubuntu 16.04

**Comment by frankong** [comment]
The issue is that ismrmrd does not compile with gcc 4.9. If you update to gcc5, then it should compile.

**Comment by LElgueddari** [comment]
Thanks for the answer I'm actually using gcc-5.4.0 and I got the same error
